### PR TITLE
Fix version check for issue 329

### PR DESCRIPTION
**Pull request by jamesooo**
https://github.com/phlipper/chef-percona/issues/329

### CODE REVIEW

**Comment by vilisseranen** [comment]
Can this PR be merged ?

**Comment by joelhandwell** [comment]
For merging PR happen, @jamesooo @vilisseranen you are welcomed to join discussion to this issue https://github.com/phlipper/chef-percona/issues/362

**Comment by jamesooo** [comment]
I'm happy to have this merged. Any action needed by me?

**Comment by damacus** [comment]
Can you rebase and run a `cookstyle -a` on this and I'll merge it in right away!

**Comment by damacus** [comment]
Closing as no progress. 

If anyone wants to pick up this PR and sort it out but our guest! 👍

**Pull request closed without merging**
